// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vmicscahrnzpmhagztmx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZtaWNzY2Focm56cG1oYWd6dG14Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzYxNTkyNTEsImV4cCI6MjA5MTczNTI1MX0.l3Q2WSCzgvy0-9fkX2GNUQ7Qgh5_lXXSo69qLXYelkQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});