// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bserzytqdrmedvglagfr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJzZXJ6eXRxZHJtZWR2Z2xhZ2ZyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzYxNzA2NDcsImV4cCI6MjA5MTc0NjY0N30.1BpiGqO8-1rZ1aSjMm2cKhNmObLYaZ4lXHOnfPXe8Dc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: typeof window !== 'undefined' ? window.localStorage : undefined,
    persistSession: typeof window !== 'undefined',
    autoRefreshToken: true,
  }
});